apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline:edit
  labels:
    banzaicloud.io/rbac: "edit"
subjects:
- kind: Group
  name: pipeline:editor
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pipeline:edit
  apiGroup: rbac.authorization.k8s.io
